#############################################################################
# Makefile for building: client
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Aug 17 11:18:59 2014
# Project:  client.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile client.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = addFriend.cpp \
		changeInf.cpp \
		changePwd.cpp \
		chatRoom.cpp \
		friendbutton.cpp \
		informationBox.cpp \
		inputTextEdit.cpp \
		links.cpp \
		loginBox.cpp \
		main.cpp \
		register.cpp \
		remark.cpp \
		showUserInf.cpp \
		tempBox.cpp \
		window.cpp moc_addFriend.cpp \
		moc_changeInf.cpp \
		moc_changePwd.cpp \
		moc_chatRoom.cpp \
		moc_friendbutton.cpp \
		moc_informationBox.cpp \
		moc_inputTextEdit.cpp \
		moc_links.cpp \
		moc_loginBox.cpp \
		moc_register.cpp \
		moc_remark.cpp \
		moc_showUserInf.cpp \
		moc_tempBox.cpp \
		moc_window.cpp
OBJECTS       = addFriend.o \
		changeInf.o \
		changePwd.o \
		chatRoom.o \
		friendbutton.o \
		informationBox.o \
		inputTextEdit.o \
		links.o \
		loginBox.o \
		main.o \
		register.o \
		remark.o \
		showUserInf.o \
		tempBox.o \
		window.o \
		moc_addFriend.o \
		moc_changeInf.o \
		moc_changePwd.o \
		moc_chatRoom.o \
		moc_friendbutton.o \
		moc_informationBox.o \
		moc_inputTextEdit.o \
		moc_links.o \
		moc_loginBox.o \
		moc_register.o \
		moc_remark.o \
		moc_showUserInf.o \
		moc_tempBox.o \
		moc_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		client.pro
QMAKE_TARGET  = client
DESTDIR       = 
TARGET        = client

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_chatRoom.h ui_informationBox.h ui_loginBox.h ui_window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: client.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile client.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile client.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/client1.0.0 || $(MKDIR) .tmp/client1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/client1.0.0/ && $(COPY_FILE) --parents addFriend.h changeInf.h changePwd.h chatRoom.h constant.h friendbutton.h informationBox.h inputTextEdit.h links.h loginBox.h register.h remark.h showUserInf.h tempBox.h window.h .tmp/client1.0.0/ && $(COPY_FILE) --parents addFriend.cpp changeInf.cpp changePwd.cpp chatRoom.cpp friendbutton.cpp informationBox.cpp inputTextEdit.cpp links.cpp loginBox.cpp main.cpp register.cpp remark.cpp showUserInf.cpp tempBox.cpp window.cpp .tmp/client1.0.0/ && $(COPY_FILE) --parents chatRoom.ui informationBox.ui loginBox.ui window.ui .tmp/client1.0.0/ && $(COPY_FILE) --parents client.ts .tmp/client1.0.0/ && (cd `dirname .tmp/client1.0.0` && $(TAR) client1.0.0.tar client1.0.0 && $(COMPRESS) client1.0.0.tar) && $(MOVE) `dirname .tmp/client1.0.0`/client1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/client1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_addFriend.cpp moc_changeInf.cpp moc_changePwd.cpp moc_chatRoom.cpp moc_friendbutton.cpp moc_informationBox.cpp moc_inputTextEdit.cpp moc_links.cpp moc_loginBox.cpp moc_register.cpp moc_remark.cpp moc_showUserInf.cpp moc_tempBox.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addFriend.cpp moc_changeInf.cpp moc_changePwd.cpp moc_chatRoom.cpp moc_friendbutton.cpp moc_informationBox.cpp moc_inputTextEdit.cpp moc_links.cpp moc_loginBox.cpp moc_register.cpp moc_remark.cpp moc_showUserInf.cpp moc_tempBox.cpp moc_window.cpp
moc_addFriend.cpp: constant.h \
		tempBox.h \
		links.h \
		addFriend.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addFriend.h -o moc_addFriend.cpp

moc_changeInf.cpp: constant.h \
		informationBox.h \
		links.h \
		ui_informationBox.h \
		changeInf.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) changeInf.h -o moc_changeInf.cpp

moc_changePwd.cpp: constant.h \
		tempBox.h \
		links.h \
		changePwd.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) changePwd.h -o moc_changePwd.cpp

moc_chatRoom.cpp: constant.h \
		links.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		chatRoom.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) chatRoom.h -o moc_chatRoom.cpp

moc_friendbutton.cpp: constant.h \
		links.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		informationBox.h \
		ui_informationBox.h \
		changeInf.h \
		remark.h \
		changePwd.h \
		friendbutton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) friendbutton.h -o moc_friendbutton.cpp

moc_informationBox.cpp: constant.h \
		links.h \
		ui_informationBox.h \
		informationBox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) informationBox.h -o moc_informationBox.cpp

moc_inputTextEdit.cpp: constant.h \
		inputTextEdit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) inputTextEdit.h -o moc_inputTextEdit.cpp

moc_links.cpp: constant.h \
		links.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) links.h -o moc_links.cpp

moc_loginBox.cpp: constant.h \
		links.h \
		register.h \
		informationBox.h \
		ui_informationBox.h \
		window.h \
		friendbutton.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		changeInf.h \
		remark.h \
		changePwd.h \
		ui_window.h \
		ui_loginBox.h \
		loginBox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) loginBox.h -o moc_loginBox.cpp

moc_register.cpp: constant.h \
		links.h \
		informationBox.h \
		ui_informationBox.h \
		register.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) register.h -o moc_register.cpp

moc_remark.cpp: constant.h \
		tempBox.h \
		links.h \
		remark.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) remark.h -o moc_remark.cpp

moc_showUserInf.cpp: constant.h \
		informationBox.h \
		links.h \
		ui_informationBox.h \
		showUserInf.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) showUserInf.h -o moc_showUserInf.cpp

moc_tempBox.cpp: constant.h \
		links.h \
		tempBox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tempBox.h -o moc_tempBox.cpp

moc_window.cpp: constant.h \
		friendbutton.h \
		links.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		informationBox.h \
		ui_informationBox.h \
		changeInf.h \
		remark.h \
		changePwd.h \
		ui_window.h \
		window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_chatRoom.h ui_informationBox.h ui_loginBox.h ui_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_chatRoom.h ui_informationBox.h ui_loginBox.h ui_window.h
ui_chatRoom.h: chatRoom.ui
	/usr/bin/uic-qt4 chatRoom.ui -o ui_chatRoom.h

ui_informationBox.h: informationBox.ui
	/usr/bin/uic-qt4 informationBox.ui -o ui_informationBox.h

ui_loginBox.h: loginBox.ui
	/usr/bin/uic-qt4 loginBox.ui -o ui_loginBox.h

ui_window.h: window.ui
	/usr/bin/uic-qt4 window.ui -o ui_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

addFriend.o: addFriend.cpp addFriend.h \
		constant.h \
		tempBox.h \
		links.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addFriend.o addFriend.cpp

changeInf.o: changeInf.cpp changeInf.h \
		constant.h \
		informationBox.h \
		links.h \
		ui_informationBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changeInf.o changeInf.cpp

changePwd.o: changePwd.cpp changePwd.h \
		constant.h \
		tempBox.h \
		links.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changePwd.o changePwd.cpp

chatRoom.o: chatRoom.cpp chatRoom.h \
		constant.h \
		links.h \
		inputTextEdit.h \
		ui_chatRoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatRoom.o chatRoom.cpp

friendbutton.o: friendbutton.cpp friendbutton.h \
		constant.h \
		links.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		informationBox.h \
		ui_informationBox.h \
		changeInf.h \
		remark.h \
		changePwd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendbutton.o friendbutton.cpp

informationBox.o: informationBox.cpp informationBox.h \
		constant.h \
		links.h \
		ui_informationBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o informationBox.o informationBox.cpp

inputTextEdit.o: inputTextEdit.cpp inputTextEdit.h \
		constant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputTextEdit.o inputTextEdit.cpp

links.o: links.cpp links.h \
		constant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o links.o links.cpp

loginBox.o: loginBox.cpp constant.h \
		loginBox.h \
		links.h \
		register.h \
		informationBox.h \
		ui_informationBox.h \
		window.h \
		friendbutton.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		changeInf.h \
		remark.h \
		changePwd.h \
		ui_window.h \
		ui_loginBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginBox.o loginBox.cpp

main.o: main.cpp loginBox.h \
		constant.h \
		links.h \
		register.h \
		informationBox.h \
		ui_informationBox.h \
		window.h \
		friendbutton.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		changeInf.h \
		remark.h \
		changePwd.h \
		ui_window.h \
		ui_loginBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

register.o: register.cpp register.h \
		constant.h \
		links.h \
		informationBox.h \
		ui_informationBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register.o register.cpp

remark.o: remark.cpp remark.h \
		constant.h \
		tempBox.h \
		links.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o remark.o remark.cpp

showUserInf.o: showUserInf.cpp showUserInf.h \
		constant.h \
		informationBox.h \
		links.h \
		ui_informationBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o showUserInf.o showUserInf.cpp

tempBox.o: tempBox.cpp tempBox.h \
		constant.h \
		links.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tempBox.o tempBox.cpp

window.o: window.cpp window.h \
		constant.h \
		friendbutton.h \
		links.h \
		chatRoom.h \
		inputTextEdit.h \
		ui_chatRoom.h \
		addFriend.h \
		tempBox.h \
		showUserInf.h \
		informationBox.h \
		ui_informationBox.h \
		changeInf.h \
		remark.h \
		changePwd.h \
		ui_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

moc_addFriend.o: moc_addFriend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addFriend.o moc_addFriend.cpp

moc_changeInf.o: moc_changeInf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changeInf.o moc_changeInf.cpp

moc_changePwd.o: moc_changePwd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changePwd.o moc_changePwd.cpp

moc_chatRoom.o: moc_chatRoom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatRoom.o moc_chatRoom.cpp

moc_friendbutton.o: moc_friendbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_friendbutton.o moc_friendbutton.cpp

moc_informationBox.o: moc_informationBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_informationBox.o moc_informationBox.cpp

moc_inputTextEdit.o: moc_inputTextEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputTextEdit.o moc_inputTextEdit.cpp

moc_links.o: moc_links.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_links.o moc_links.cpp

moc_loginBox.o: moc_loginBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginBox.o moc_loginBox.cpp

moc_register.o: moc_register.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_register.o moc_register.cpp

moc_remark.o: moc_remark.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_remark.o moc_remark.cpp

moc_showUserInf.o: moc_showUserInf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_showUserInf.o moc_showUserInf.cpp

moc_tempBox.o: moc_tempBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tempBox.o moc_tempBox.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

